---
abstract: 'AnyEvent::Processor - Base class for processing something'
author:
  - 'Frédéric Demians <f.demians@tamil.fr>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Processor
requires:
  AnyEvent: 0
  Moose: 0
  Moose::Role: 0
  perl: 5.010
resources:
  repository: http://git.tamil.fr/git/AnyEvent-Processor
version: 0.003
